CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(50),
    Age NUMBER,
    Balance NUMBER,
    IsVIP VARCHAR2(5)
);

CREATE TABLE Loans (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    InterestRate NUMBER,
    DueDate DATE,
    FOREIGN KEY(CustomerID)
    REFERENCES Customers(CustomerID)
);

INSERT INTO Customers
VALUES(1,'John',65,15000,'FALSE');

INSERT INTO Customers
VALUES(2,'Alice',35,5000,'FALSE');

INSERT INTO Customers
VALUES(3,'David',70,25000,'FALSE');

INSERT INTO Customers
VALUES(4,'Emma',55,12000,'FALSE');

INSERT INTO Loans
VALUES(101,1,8,TRUNC(SYSDATE)+15);

INSERT INTO Loans
VALUES(102,2,10,TRUNC(SYSDATE)+40);

INSERT INTO Loans
VALUES(103,3,9,TRUNC(SYSDATE)+20);

INSERT INTO Loans
VALUES(104,4,11,TRUNC(SYSDATE)+10);

COMMIT;